### ISSUE TITLE
mapping topic cluster to conversation & moderation 

### ISSUE THREAD

**Issue by annabechang** [HannahKirk/prism-alignment#1]
Hi,
 
Great research! 
Thanks for making the data and code available. 

I am considering conducting research using your data and have the following question: 

1. Is there a mapping between the topic clustering (cluster_id) to the prompt / prompt id/ conversation or anything like that?
(i saw the cluster id in the opening_prompt_cluster_df_original.csv file, but i couldn't really map it back to the conversation.) 

2. is the moderation run on the user_prompt, and not on the model_response? 

Thank you,

**Comment by HannahKirk** [comment]
Hi there! 

Thanks for messaging :) You should be able to map the text id back to the cluster id with this text-level file: results/clusters/opening_prompt_text_df_original.csv

Moderation is run on every major type of text instance - model response, user_prompt, open_feedback (from conversations), as well as system_string, self_description (from survey).

All the best!
